### Anéis de polinómios e anéis quociente

In [1]:
R = PolynomialRing(ZZ,name='w')
print(R)

Univariate Polynomial Ring in w over Integer Ring


In [2]:
N = 16
w = R.gen()
r = 1 + w + w^N
print(r)
print(r.is_irreducible())

w^16 + w + 1
True


In [3]:
I = R.ideal(r)
K.<z> = QuotientRing(R,I)
print(K)

Univariate Quotient Polynomial Ring in z over Integer Ring with modulus w^16 + w + 1


In [4]:
K.random_element()

z^15 + 4*z^14 - z^13 + 11*z^12 + z^10 + 2*z^9 + z^6 - z^5 + 4*z^4 + z^3 - 3*z^2 + 3*z - 3

In [5]:
z = K.gen()
print(z^256)

try:
    print(z^(-256))
except Exception as ex:
    print("Exception",ex.args)
          

16*z^15 + 120*z^14 + 560*z^13 + 1820*z^12 + 4368*z^11 + 8008*z^10 + 11440*z^9 + 12870*z^8 + 11440*z^7 + 8008*z^6 + 4368*z^5 + 1820*z^4 + 560*z^3 + 120*z^2 + 15*z
Exception ('The base ring (=Integer Ring) is not a field',)


$K$ não é um corpo, apesar de $(1+w+w^256)$ ser irredutível, porque os coeficientes do polinómio inicial não pertencem a um corpo.

In [6]:
q = 311

R = PolynomialRing(GF(q),name='w')
w = R.gen()
r = (1 + w + w^256)
print(r.is_irreducible())

I = R.ideal(r)
K.<z> = QuotientRing(R,I)
print(K)

True
Univariate Quotient Polynomial Ring in z over Finite Field of size 311 with modulus w^256 + w + 1


Agora $311$ é primo e os coeficientes dos polinómios pertencem ao corpo finito $\mathsf{GF}(311)$.

Porque com este corpo de coeficientes o polinómio $(1+w+w^{256})$ é irreducível, o anel quociente $K$ já é um corpo.

In [ ]:
z = K.gen()

try:
    print(z^256)
    print(z^(-256))
except Exception as ex:
    print("Exception",ex.args)